import type { AbilityVisual, EffectFamily } from './types';
import type { MoveId } from '../animation/types';

// Each row chooses geometry, choreography, palette and multiplicity. Costs and rules stay in the source brief.
const v = (family: EffectFamily, color: string, motion: MoveId, scale = 1, count = 1,
  style: AbilityVisual['style'] = 'runes', pose?: AbilityVisual['pose'], accent = '#f7f3df'): AbilityVisual =>
  ({ family, color, accent, motion, scale, count, style, pose });

export const ABILITY_VISUALS: Readonly<Record<string, AbilityVisual>> = {
  'power-strike': v('slash', '#ffc66b', 'heavy-attack', 1.25, 1, 'embers'),
  'shield-bash': v('impact', '#e7c783', 'light-attack', .8, 1, 'shards', 'thrust'),
  rend: v('slash', '#e95251', 'light-attack', .9, 3, 'arc'),
  'crushing-blow': v('impact', '#edaa60', 'two-handed-strike', 1.35, 8, 'shards'),
  lunge: v('impact', '#f4e8ba', 'idle', .6, 1, 'shards', 'thrust'),
  sweep: v('slash', '#dfba79', 'heavy-attack', 1.5, 1, 'arc'),
  whirlwind: v('slash', '#e2cb9b', 'whirlwind', 1.65, 4, 'arc'),
  disarm: v('slash', '#f3f0d4', 'light-attack', .55, 2, 'shards'),
  'leap-slam': v('impact', '#ffb859', 'running-leap', 1.9, 16, 'shards'),
  'battle-cry': v('song', '#ffce80', 'combat-idle', 1.6, 3, 'runes', 'shout'),
  riposte: v('slash', '#fff0b4', 'light-attack', .75, 1, 'arc'),
  berserk: v('aura', '#e34832', 'combat-idle', 1.25, 6, 'embers', 'shout'),
  'aimed-shot': v('projectile', '#dcebb7', 'idle', .65, 1, 'feathers', 'bow'),
  snare: v('trap', '#a6bb8d', 'idle', .8, 1, 'runes', 'kneel'),
  'crippling-shot': v('projectile', '#bccd79', 'idle', .7, 1, 'feathers', 'bow'),
  disengage: v('stealth', '#a4d0ae', 'idle', .9, 4, 'feathers'),
  'hunters-mark': v('mark', '#ff283c', 'cast', .8, 4, 'runes'),
  'double-shot': v('projectile', '#c4e299', 'idle', .7, 2, 'feathers', 'bow'),
  'fleet-foot': v('aura', '#b2debc', 'run', .6, 2, 'feathers'),
  'beast-call': v('song', '#b8d08a', 'idle', 1.1, 3, 'feathers', 'shout'),
  'piercing-arrow': v('projectile', '#ffe8a4', 'idle', .85, 1, 'feathers', 'bow'),
  volley: v('volley', '#dfc88b', 'idle', 1.5, 18, 'feathers', 'bow'),
  'magic-arrow': v('projectile', '#b09bff', 'energy-missiles', .65, 1, 'wisps', undefined, '#e8d7ff'),
  fireball: v('projectile', '#ff762a', 'fireball', 1.2, 1, 'embers', undefined, '#ffe09b'),
  'ice-shard': v('projectile', '#65d7ff', 'cast', 1, 1, 'shards', undefined, '#e2fbff'),
  blink: v('stealth', '#8d9fff', 'cast', 1.2, 5, 'runes'),
  lightning: v('lightning', '#a5c5ff', 'lightning', 1.25, 1, 'arc'),
  'mana-shield': v('shield', '#8ea0ff', 'healing', 1.1, 6, 'runes'),
  'frost-nova': v('nova', '#87e7ff', 'cast', 1.65, 24, 'shards'),
  'chain-lightning': v('lightning', '#b7d0ff', 'lightning', 1.2, 4, 'arc'),
  'arcane-mastery': v('aura', '#c0a5ff', 'idle', .75, 3, 'runes'),
  meteor: v('meteor', '#ff7031', 'cast', 1.8, 1, 'embers', 'shout'),
  hex: v('mark', '#c488e8', 'cast', .85, 3, 'runes'),
  'eldritch-bolt': v('projectile', '#8be2c2', 'cast', .85, 1, 'wisps', undefined, '#d0ffb0'),
  'stone-skin': v('shield', '#ad9c85', 'healing', 1.05, 14, 'shards'),
  ward: v('shield', '#83cbbb', 'cast', 1.8, 8, 'runes'),
  transmute: v('portal', '#ffd78b', 'cast', .8, 6, 'shards', 'kneel'),
  'spell-plague': v('mark', '#bddb58', 'cast', 1.2, 7, 'wisps'),
  rift: v('portal', '#a774f0', 'cast', 1.7, 9, 'wisps', undefined, '#eda6ff'),
  'elemental-kin': v('aura', '#72d6ba', 'idle', .85, 4, 'shards'),
  'life-drain': v('drain', '#c45177', 'cast', 1.05, 3, 'wisps'),
  'raise-skeleton': v('portal', '#b2d67c', 'cast', 1.1, 8, 'shards'),
  'summon-imp': v('portal', '#f37b54', 'cast', .8, 5, 'embers'),
  'bone-spear': v('projectile', '#e5d6ac', 'cast', 1.2, 1, 'shards'),
  fear: v('nova', '#9780c2', 'cast', 1.75, 6, 'wisps', 'shout'),
  'curse-of-weakness': v('mark', '#a383b7', 'cast', 1.05, 5, 'wisps'),
  'corpse-explosion': v('impact', '#b6cd63', 'cast', 1.65, 18, 'shards'),
  'summon-hound': v('portal', '#7e70bd', 'cast', 1.35, 4, 'wisps'),
  'lich-form': v('aura', '#8ce8ae', 'healing', 1.6, 10, 'wisps', 'shout'),
  'raise-champion': v('portal', '#c9e4ad', 'cast', 1.8, 12, 'shards'),
  heal: v('heal', '#83f0b2', 'healing', .9, 3, 'wisps'),
  cleanse: v('nova', '#e7fff0', 'healing', 1.1, 7, 'feathers'),
  bless: v('aura', '#f4dd95', 'healing', 1, 5, 'runes'),
  'consecrate-weapon': v('aura', '#ffd779', 'combat-idle', .8, 4, 'embers'),
  'greater-heal': v('heal', '#abffd7', 'healing', 1.4, 7, 'wisps'),
  smite: v('lightning', '#fff0bc', 'cast', 1.6, 1, 'runes'),
  sanctuary: v('shield', '#f9e7b6', 'cast', 2.1, 12, 'feathers'),
  resurrect: v('heal', '#fff5c9', 'healing', 1.8, 9, 'feathers', 'kneel'),
  'lay-on-hands': v('heal', '#ffeab3', 'healing', 1.6, 12, 'runes'),
  hide: v('stealth', '#718496', 'idle', .8, 3, 'wisps', 'kneel'),
  'poison-blade': v('aura', '#abc855', 'combat-idle', .7, 5, 'wisps'),
  'pick-pocket': v('mark', '#dfc886', 'light-attack', .35, 3, 'embers', 'thrust'),
  backstab: v('slash', '#c65b72', 'light-attack', .85, 2, 'arc', 'thrust'),
  shadowstep: v('stealth', '#9276bf', 'dodge', 1.3, 6, 'wisps'),
  evasion: v('aura', '#a0b5ce', 'combat-idle', 1, 5, 'feathers'),
  'expose-weakness': v('mark', '#efc879', 'cast', .85, 4, 'runes', 'thrust'),
  vanish: v('stealth', '#a18cbd', 'idle', 1.5, 8, 'wisps'),
  provoke: v('song', '#ef956e', 'cast', 1.2, 2, 'runes', 'music'),
  peace: v('song', '#c1dfc1', 'cast', 1.35, 3, 'feathers', 'music'),
  discord: v('song', '#d398d4', 'cast', 1.25, 5, 'arc', 'music'),
  'marching-song': v('song', '#86cec3', 'walk', 1.25, 4, 'runes', 'music'),
  'war-drum': v('song', '#df9c60', 'combat-idle', 1.4, 6, 'runes', 'music'),
  lullaby: v('song', '#aaaee5', 'cast', 1.4, 7, 'wisps', 'music'),
  jump: v('impact', '#c6ba9c', 'jump-launch', .35, 4, 'shards'),
  sprint: v('aura', '#d4cfb3', 'run', .55, 2, 'feathers'),
  bandage: v('heal', '#e3e0c4', 'healing', .45, 2, 'feathers', 'kneel'),
  meditate: v('aura', '#98bddd', 'idle', .8, 4, 'wisps', 'kneel'),
};
