import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { animateIncubatorHouse, createIncubatorHouse } from '../assets/incubatorHouse.js';
const host = document.querySelector('#canvas-host'); const stats = document.querySelector('#stats'); const renderer = new THREE.WebGLRenderer({ antialias: true, preserveDrawingBuffer: true }); renderer.setPixelRatio(Math.min(devicePixelRatio || 1, 2)); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFShadowMap; renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.08; host.appendChild(renderer.domElement);
const scene = new THREE.Scene(); scene.background = new THREE.Color(0xf7f0e6); const camera = new THREE.PerspectiveCamera(32, 1, 0.01, 100); camera.position.set(-3.1, 4.25, 10.2); const controls = new OrbitControls(camera, renderer.domElement); controls.target.set(-0.08, 0.92, 0.02); controls.enableDamping = true; controls.enablePan = false; controls.minDistance = 4.8; controls.maxDistance = 13;
scene.add(new THREE.HemisphereLight(0xfff9ef, 0x708080, 2)); const key = new THREE.DirectionalLight(0xffe0bf, 3); key.position.set(-4.2, 5.5, 4.8); key.castShadow = true; key.shadow.mapSize.set(2048, 2048); scene.add(key); const fill = new THREE.DirectionalLight(0xddeceb, 1.25); fill.position.set(4, 3.2, 3.5); scene.add(fill); const rim = new THREE.DirectionalLight(0xfff0d8, 0.7); rim.position.set(1.5, 4, -4); scene.add(rim);
const ground = new THREE.Mesh(new THREE.CircleGeometry(4.2, 64), new THREE.ShadowMaterial({ color: 0x4a4036, opacity: 0.11, transparent: true })); ground.rotation.x = -Math.PI / 2; ground.receiveShadow = true; scene.add(ground); const asset = createIncubatorHouse(); scene.add(asset);
function resize() { renderer.setSize(host.clientWidth, host.clientHeight, false); camera.aspect = host.clientWidth / Math.max(1, host.clientHeight); camera.updateProjectionMatrix(); } resize(); new ResizeObserver(resize).observe(host); const start = performance.now(); let reviewCaptured = false; function frame(now) { animateIncubatorHouse(asset, (now - start) / 1000); controls.update(); renderer.render(scene, camera); if (!reviewCaptured && now - start > 800) { reviewCaptured = true; renderer.domElement.toBlob(async (blob) => { if (!blob) return; const response = await fetch(`/__artifact__?path=${encodeURIComponent('review/incubator-house/browser-review.png')}`, { method: 'POST', headers: { 'Content-Type': 'image/png' }, body: blob }); window.__INCUBATOR_HOUSE_REVIEW_CAPTURED__ = response.ok; }, 'image/png'); } requestAnimationFrame(frame); } requestAnimationFrame(frame);
let meshes = 0; let triangles = 0; asset.traverse((node) => { if (!node.visible || !node.isMesh) return; meshes += 1; triangles += (node.geometry.index?.count ?? node.geometry.getAttribute('position')?.count ?? 0) / 3; }); stats.textContent = `${meshes} visible meshes · ${Math.round(triangles).toLocaleString()} triangles · 5 material families`; window.__INCUBATOR_HOUSE_REVIEW_READY__ = true; window.__INCUBATOR_HOUSE_REVIEW_STATE__ = { asset, runtime: asset.userData.sculptRuntime, rig: asset.userData.incubatorHouseRig };
