import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { collectSceneStats } from '../export/handPumpExportUtils.js';
const SOURCE = 'source-glb/raised-bed.source.glb', OPTIMIZED = 'optimized-glb/Raised-Bed.glb', EXPORT = 'manifests/raised-bed.export.json', RESULT = 'manifests/raised-bed.validation.json', TOLERANCE = 0.006;
const check = (name, passed, details = {}) => ({ name, passed, details }); const names = (root, predicate) => { const result = []; root.traverse((node) => { if (predicate(node)) result.push(node.name); }); return result.sort(); }; const missing = (actual, expected) => expected.filter((value) => !new Set(actual).has(value));
async function read(path) { return (await fetch(path)).json(); } async function extensions(path) { const buffer = await (await fetch(path)).arrayBuffer(), view = new DataView(buffer), length = view.getUint32(12, true); return JSON.parse(new TextDecoder().decode(new Uint8Array(buffer, 20, length)).trim()).extensionsUsed ?? []; } async function save(value) { await fetch(`/__artifact__?path=${encodeURIComponent(RESULT)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(value, null, 2) }); }
export async function validateRaisedBedExports() {
  const [manifest, sourceGltf, optimizedGltf, sourceExtensions, optimizedExtensions] = await Promise.all([read(EXPORT), new GLTFLoader().loadAsync(SOURCE), new GLTFLoader().loadAsync(OPTIMIZED), extensions(SOURCE), extensions(OPTIMIZED)]);
  const source = sourceGltf.scene, optimized = optimizedGltf.scene, sourceStats = collectSceneStats(source), optimizedStats = collectSceneStats(optimized), root = source.getObjectByName('raised-bed-root'), semantics = root?.userData?.sourceSemantics, allNames = names(source, () => true), socketNames = names(source, (node) => Boolean(node.userData.socket)), colliderNames = names(source, (node) => Boolean(node.userData.collider));
  const delta = Math.max(...sourceStats.bounds.min.map((value, index) => Math.abs(value - optimizedStats.bounds.min[index])), ...sourceStats.bounds.max.map((value, index) => Math.abs(value - optimizedStats.bounds.max[index]))); const forbidden = new Set(['KHR_draco_mesh_compression', 'EXT_meshopt_compression']);
  const checks = [check('source scene is nonempty', sourceStats.meshes > 0, { meshes: sourceStats.meshes }), check('optimized scene is nonempty', optimizedStats.meshes > 0, { meshes: optimizedStats.meshes }), check('source ground contact', Math.abs(sourceStats.bounds.min[1]) <= TOLERANCE, { minY: sourceStats.bounds.min[1] }), check('optimized ground contact', Math.abs(optimizedStats.bounds.min[1]) <= TOLERANCE, { minY: optimizedStats.bounds.min[1] }), check('triangle budget', sourceStats.triangles < 1500 && optimizedStats.triangles < 1500, { source: sourceStats.triangles, optimized: optimizedStats.triangles }), check('optimized draw-call target', optimizedStats.drawCalls >= 1 && optimizedStats.drawCalls <= 4, { drawCalls: optimizedStats.drawCalls }), check('source pivots survive reload', missing(allNames, manifest.source.requiredPivotNames).length === 0, { missing: missing(allNames, manifest.source.requiredPivotNames) }), check('source sockets survive reload', missing(socketNames, manifest.source.requiredSocketNames).length === 0, { missing: missing(socketNames, manifest.source.requiredSocketNames) }), check('source collider survives reload', missing(colliderNames, manifest.source.requiredColliderNames).length === 0, { missing: missing(colliderNames, manifest.source.requiredColliderNames) }), check('source static semantics survive reload', Boolean(semantics) && semantics.animationChannels?.length === 0, { channels: semantics?.animationChannels?.length ?? 0 }), check('no decoder dependency', sourceExtensions.every((value) => !forbidden.has(value)) && optimizedExtensions.every((value) => !forbidden.has(value)), { sourceExtensions, optimizedExtensions }), check('static bounds match source', delta <= TOLERANCE, { delta }), check('optimized export reduces draw calls', optimizedStats.drawCalls < sourceStats.drawCalls, { source: sourceStats.drawCalls, optimized: optimizedStats.drawCalls })];
  const result = { schemaVersion: 1, assetId: 'raised-bed', coordinateSystem: { up: 'Y', forward: '+Z', unit: 'metre', groundY: 0 }, result: checks.every((item) => item.passed) ? 'pass' : 'fail', checks, source: sourceStats, optimized: optimizedStats }; await save(result); return result;
}
const output = document.querySelector('#output'); window.__RAISED_BED_VALIDATION_READY__ = false; try { window.__RAISED_BED_VALIDATION_RESULT__ = await validateRaisedBedExports(); output.textContent = JSON.stringify(window.__RAISED_BED_VALIDATION_RESULT__, null, 2); window.__RAISED_BED_VALIDATION_READY__ = true; } catch (error) { output.textContent = String(error.stack || error.message); window.__RAISED_BED_VALIDATION_ERROR__ = String(error.stack || error.message); }
