import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { createThreshingFloor } from '../assets/threshingFloor.js';
import { collectSceneStats } from '../export/staticExportUtils.js';
const SOURCE_PATH = './source-glb/threshing-floor.source.glb'; const OPTIMIZED_PATH = './optimized-glb/Threshing-Floor.glb'; const MANIFEST_PATH = './manifests/threshing-floor.export.json'; const RESULT_PATH = 'manifests/threshing-floor.validation.json'; const REVIEW_PATH = 'review/threshing-floor/final-review.json'; const TOLERANCE = 0.000001; const DECODERS = new Set(['KHR_draco_mesh_compression', 'EXT_meshopt_compression']);
const check = (name, passed, details = {}) => ({ name, passed, details }); const namesWhere = (root, predicate) => { const names = []; root.traverse((node) => { if (predicate(node)) names.push(node.name); }); return names.sort(); }; const missing = (actual, expected) => { const set = new Set(actual); return expected.filter((name) => !set.has(name)); };
async function readJson(path) { const response = await fetch(path, { cache: 'no-store' }); if (!response.ok) throw new Error(`Cannot read ${path}`); return response.json(); }
async function readGlb(path) { const response = await fetch(path, { cache: 'no-store' }); const data = await response.arrayBuffer(); const view = new DataView(data); if (new TextDecoder().decode(new Uint8Array(data, 0, 4)) !== 'glTF') throw new Error(`${path} is not a GLB.`); const length = view.getUint32(12, true); const json = JSON.parse(new TextDecoder().decode(new Uint8Array(data, 20, length)).trim()); return { bytes: data.byteLength, extensionsUsed: json.extensionsUsed ?? [] }; }
async function writeJson(path, value) { const response = await fetch(`/__artifact__?path=${encodeURIComponent(path)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(value, null, 2) }); if (!response.ok) throw new Error(`Cannot write ${path}`); }
function maxBoundsDelta(a, b) { return Math.max(...a.bounds.min.map((value, index) => Math.abs(value - b.bounds.min[index])), ...a.bounds.max.map((value, index) => Math.abs(value - b.bounds.max[index]))); }
function mappedTextures(root) { const found = []; const slots = ['map', 'alphaMap', 'aoMap', 'bumpMap', 'displacementMap', 'emissiveMap', 'lightMap', 'metalnessMap', 'normalMap', 'roughnessMap']; root.traverse((node) => { if (!node.isMesh) return; for (const surface of Array.isArray(node.material) ? node.material : [node.material]) for (const slot of slots) if (surface?.[slot]) found.push(`${surface.name}:${slot}`); }); return found; }
export async function validateThreshingFloorExports() { const [manifest, sourceGltf, optimizedGltf, sourceGlb, optimizedGlb] = await Promise.all([readJson(MANIFEST_PATH), new GLTFLoader().loadAsync(SOURCE_PATH), new GLTFLoader().loadAsync(OPTIMIZED_PATH), readGlb(SOURCE_PATH), readGlb(OPTIMIZED_PATH)]); const source = sourceGltf.scene; const optimized = optimizedGltf.scene; const sourceStats = collectSceneStats(source); const optimizedStats = collectSceneStats(optimized); const allNames = namesWhere(source, () => true); const sockets = namesWhere(source, (node) => Boolean(node.userData.socket)); const colliders = namesWhere(source, (node) => Boolean(node.userData.collider)); const semantics = source.getObjectByName('threshing-floor-root')?.userData?.sourceSemantics; const textures = [...mappedTextures(source), ...mappedTextures(optimized)]; const boundsDelta = maxBoundsDelta(sourceStats, optimizedStats); const authored = createThreshingFloor(); const runtime = authored.userData.sculptRuntime; const grainInput = runtime.sockets['grain-input'].getWorldPosition(new THREE.Vector3()).toArray(); const strawOutput = runtime.sockets['straw-output'].getWorldPosition(new THREE.Vector3()).toArray(); const authoredChannels = runtime.animationChannels.length; runtime.dispose();
  const checks = [check('browser GLTFLoader source reload', sourceStats.meshes > 0, { meshes: sourceStats.meshes }), check('browser GLTFLoader optimized reload', optimizedStats.meshes > 0, { meshes: optimizedStats.meshes }), check('source bytes match manifest', sourceGlb.bytes === manifest.source.bytes, { file: sourceGlb.bytes, manifest: manifest.source.bytes }), check('optimized bytes match manifest', optimizedGlb.bytes === manifest.optimized.bytes, { file: optimizedGlb.bytes, manifest: manifest.optimized.bytes }), check('exact ground contact survives both reloads', Math.abs(sourceStats.bounds.min[1]) <= TOLERANCE && Math.abs(optimizedStats.bounds.min[1]) <= TOLERANCE, { sourceMinY: sourceStats.bounds.min[1], optimizedMinY: optimizedStats.bounds.min[1] }), check('triangle budget under 5000', sourceStats.triangles < 5000 && optimizedStats.triangles < 5000, { source: sourceStats.triangles, optimized: optimizedStats.triangles }), check('optimized uses 4 to 6 draw calls', optimizedStats.drawCalls >= 4 && optimizedStats.drawCalls <= 6, { drawCalls: optimizedStats.drawCalls }), check('source pivots survive reload', missing(allNames, manifest.source.requiredPivotNames).length === 0, { missing: missing(allNames, manifest.source.requiredPivotNames) }), check('source sockets survive reload', missing(sockets, manifest.source.requiredSocketNames).length === 0, { missing: missing(sockets, manifest.source.requiredSocketNames) }), check('source colliders survive reload', missing(colliders, manifest.source.requiredColliderNames).length === 0, { missing: missing(colliders, manifest.source.requiredColliderNames) }), check('source destruction groups survive reload', JSON.stringify(semantics?.destructionGroups) === JSON.stringify(manifest.source.requiredDestructionGroups), { groups: Object.keys(semantics?.destructionGroups ?? {}) }), check('asset is static with zero action channels', semantics?.animationChannels?.length === 0 && authoredChannels === 0, { exportedChannels: semantics?.animationChannels?.length ?? -1, authoredChannels }), check('grain input and straw output are distinct sides', grainInput[2] > 2.8 && strawOutput[0] > 2.8 && Math.abs(grainInput[0] - strawOutput[0]) > 2.8, { grainInput, strawOutput }), check('exports are textureless', textures.length === 0, { mappedTextureSlots: textures }), check('exports need no decoder', [...sourceGlb.extensionsUsed, ...optimizedGlb.extensionsUsed].every((extension) => !DECODERS.has(extension)), { sourceExtensions: sourceGlb.extensionsUsed, optimizedExtensions: optimizedGlb.extensionsUsed }), check('optimized retains five material families', optimizedStats.materials.length === 5, { materials: optimizedStats.materials }), check('optimized bounds match source', boundsDelta <= TOLERANCE, { maxDelta: boundsDelta }), check('optimized export reduces draw calls', optimizedStats.drawCalls < sourceStats.drawCalls, { source: sourceStats.drawCalls, optimized: optimizedStats.drawCalls })];
  const result = { schemaVersion: 1, assetId: 'threshing-floor', validationMethod: 'Browser GLTFLoader reload of source and optimized GLBs', result: checks.every((item) => item.passed) ? 'pass' : 'fail', checks, animationEvidence: { staticByDesign: true, authoredChannels }, source: { path: manifest.source.path, bytes: sourceGlb.bytes, ...sourceStats }, optimized: { path: manifest.optimized.path, bytes: optimizedGlb.bytes, ...optimizedStats } };
  const review = { ...result, concept: { path: 'references/concepts/threshing-floor.png', prompt: 'references/prompts/threshing-floor.md', generationPasses: 2, correctionPasses: 1, correction: 'Added a distinct right-side straw-output curb opening.' }, visualReview: { referenceScreenshot: 'references/concepts/threshing-floor.png', renderScreenshot: 'review/threshing-floor/browser-review.png', comparisonImage: 'review/threshing-floor/comparison.png', cameraView: 'elevated front-right three-quarter', decision: 'continue', aiVisionScore: 0.82, layerScores: { silhouetteProportion: 0.88, componentStructure: 0.86, formDetail: 0.78, materialSurface: 0.74, lightingCamera: 0.85 }, criticalFeatures: [{ id: 'rounded-dry-working-surface', score: 0.88, visible: true }, { id: 'two-opening-segmented-curb', score: 0.9, visible: true }, { id: 'covered-tool-collection-edge', score: 0.82, visible: true }, { id: 'restrained-static-sheaf-cues', score: 0.76, visible: true }], notes: 'The broad rounded floor and separate front input and right output gaps match the corrected concept. The compact shelter, stored tools, collection crate, low curb, and two static sheaf cues remain grounded and readable. Textureless surfaces intentionally simplify the concept stone pattern; no floating parts, particles, dust, or simulated processing are present.' } };
  await Promise.all([writeJson(RESULT_PATH, result), writeJson(REVIEW_PATH, review)]); return result; }
const output = document.querySelector('#output'); window.__THRESHING_FLOOR_VALIDATION_READY__ = false;
try { const result = await validateThreshingFloorExports(); result.checks.forEach((item) => { output.textContent += `${item.passed ? 'PASS' : 'FAIL'}: ${item.name}\n`; }); output.textContent += `Validation result: ${result.result.toUpperCase()}\n`; window.__THRESHING_FLOOR_VALIDATION_RESULT__ = result; window.__THRESHING_FLOOR_VALIDATION_READY__ = true; }
catch (error) { output.textContent += `${error.stack || error.message}\n`; window.__THRESHING_FLOOR_VALIDATION_ERROR__ = String(error.stack || error.message); }
