import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { createHayRack } from '../assets/hayRack.js';
import { collectSceneStats } from '../export/staticExportUtils.js';
const SOURCE_PATH = './source-glb/hay-rack.source.glb'; const OPTIMIZED_PATH = './optimized-glb/Hay-Rack.glb'; const MANIFEST_PATH = './manifests/hay-rack.export.json'; const RESULT_PATH = 'manifests/hay-rack.validation.json'; const REVIEW_PATH = 'review/hay-rack/final-review.json'; const TOLERANCE = 0.000001; const DECODERS = new Set(['KHR_draco_mesh_compression', 'EXT_meshopt_compression']);
const check = (name, passed, details = {}) => ({ name, passed, details }); const namesWhere = (root, predicate) => { const names = []; root.traverse((node) => { if (predicate(node)) names.push(node.name); }); return names.sort(); }; const missing = (actual, expected) => { const set = new Set(actual); return expected.filter((name) => !set.has(name)); };
async function readJson(path) { const response = await fetch(path, { cache: 'no-store' }); if (!response.ok) throw new Error(`Cannot read ${path}`); return response.json(); }
async function readGlb(path) { const response = await fetch(path, { cache: 'no-store' }); const data = await response.arrayBuffer(); const view = new DataView(data); if (new TextDecoder().decode(new Uint8Array(data, 0, 4)) !== 'glTF') throw new Error(`${path} is not a GLB.`); const length = view.getUint32(12, true); const json = JSON.parse(new TextDecoder().decode(new Uint8Array(data, 20, length)).trim()); return { bytes: data.byteLength, extensionsUsed: json.extensionsUsed ?? [] }; }
async function writeJson(path, value) { const response = await fetch(`/__artifact__?path=${encodeURIComponent(path)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(value, null, 2) }); if (!response.ok) throw new Error(`Cannot write ${path}`); }
function maxBoundsDelta(a, b) { return Math.max(...a.bounds.min.map((v, i) => Math.abs(v - b.bounds.min[i])), ...a.bounds.max.map((v, i) => Math.abs(v - b.bounds.max[i]))); }
function mappedTextures(root) { const found = []; const slots = ['map', 'alphaMap', 'aoMap', 'bumpMap', 'displacementMap', 'emissiveMap', 'lightMap', 'metalnessMap', 'normalMap', 'roughnessMap']; root.traverse((node) => { if (!node.isMesh) return; for (const surface of Array.isArray(node.material) ? node.material : [node.material]) for (const slot of slots) if (surface?.[slot]) found.push(`${surface.name}:${slot}`); }); return found; }
export async function validateHayRackExports() {
  const [manifest, sourceGltf, optimizedGltf, sourceGlb, optimizedGlb] = await Promise.all([readJson(MANIFEST_PATH), new GLTFLoader().loadAsync(SOURCE_PATH), new GLTFLoader().loadAsync(OPTIMIZED_PATH), readGlb(SOURCE_PATH), readGlb(OPTIMIZED_PATH)]);
  const source = sourceGltf.scene; const optimized = optimizedGltf.scene; const sourceStats = collectSceneStats(source); const optimizedStats = collectSceneStats(optimized); const allNames = namesWhere(source, () => true); const sockets = namesWhere(source, (n) => Boolean(n.userData.socket)); const colliders = namesWhere(source, (n) => Boolean(n.userData.collider)); const semantics = source.getObjectByName('hay-rack-root')?.userData?.sourceSemantics; const authored = createHayRack(); const runtime = authored.userData.sculptRuntime; const pivotRotations = Object.values(runtime.pivots).map((node) => node.rotation.toArray().slice(0, 3)); authored.userData.sculptRuntime.dispose(); const textures = [...mappedTextures(source), ...mappedTextures(optimized)]; const boundsDelta = maxBoundsDelta(sourceStats, optimizedStats);
  const checks = [
    check('browser GLTFLoader source reload', sourceStats.meshes > 0, { meshes: sourceStats.meshes }), check('browser GLTFLoader optimized reload', optimizedStats.meshes > 0, { meshes: optimizedStats.meshes }), check('source bytes match manifest', sourceGlb.bytes === manifest.source.bytes, { file: sourceGlb.bytes, manifest: manifest.source.bytes }), check('optimized bytes match manifest', optimizedGlb.bytes === manifest.optimized.bytes, { file: optimizedGlb.bytes, manifest: manifest.optimized.bytes }),
    check('exact ground contact survives both reloads', Math.abs(sourceStats.bounds.min[1]) <= TOLERANCE && Math.abs(optimizedStats.bounds.min[1]) <= TOLERANCE, { sourceMinY: sourceStats.bounds.min[1], optimizedMinY: optimizedStats.bounds.min[1] }), check('triangle budget under 1500', sourceStats.triangles < 1500 && optimizedStats.triangles < 1500, { source: sourceStats.triangles, optimized: optimizedStats.triangles }), check('optimized uses 3 to 5 draw calls', optimizedStats.drawCalls >= 3 && optimizedStats.drawCalls <= 5, { drawCalls: optimizedStats.drawCalls }),
    check('source pivots survive reload', missing(allNames, manifest.source.requiredPivotNames).length === 0, { missing: missing(allNames, manifest.source.requiredPivotNames) }), check('source sockets survive reload', missing(sockets, manifest.source.requiredSocketNames).length === 0, { missing: missing(sockets, manifest.source.requiredSocketNames) }), check('source colliders survive reload', missing(colliders, manifest.source.requiredColliderNames).length === 0, { missing: missing(colliders, manifest.source.requiredColliderNames) }), check('source destruction groups survive reload', JSON.stringify(semantics?.destructionGroups) === JSON.stringify(manifest.source.requiredDestructionGroups), { groups: Object.keys(semantics?.destructionGroups ?? {}) }),
    check('rack is deliberately static', semantics?.animationChannels?.length === 0 && manifest.source.actionChannels.length === 0, { actionChannels: semantics?.animationChannels ?? [] }), check('all authored pivots retain rest rotations', pivotRotations.every((rotation) => rotation.every((value) => value === 0)), { pivotRotations }), check('exports are textureless', textures.length === 0, { mappedTextureSlots: textures }), check('exports need no decoder', [...sourceGlb.extensionsUsed, ...optimizedGlb.extensionsUsed].every((ext) => !DECODERS.has(ext)), { sourceExtensions: sourceGlb.extensionsUsed, optimizedExtensions: optimizedGlb.extensionsUsed }), check('optimized retains four material families', optimizedStats.materials.length === 4, { materials: optimizedStats.materials }), check('optimized bounds match source', boundsDelta <= TOLERANCE, { maxDelta: boundsDelta }), check('optimized export reduces draw calls', optimizedStats.drawCalls < sourceStats.drawCalls, { source: sourceStats.drawCalls, optimized: optimizedStats.drawCalls }),
  ];
  const result = { schemaVersion: 1, assetId: 'hay-rack', validationMethod: 'Browser GLTFLoader reload of source and optimized GLBs', result: checks.every((item) => item.passed) ? 'pass' : 'fail', checks, animationEvidence: { static: true, reason: 'Open refill mouth is visible; no latch or door is modeled.', actionChannels: [] }, source: { path: manifest.source.path, bytes: sourceGlb.bytes, ...sourceStats }, optimized: { path: manifest.optimized.path, bytes: optimizedGlb.bytes, ...optimizedStats } };
  await Promise.all([writeJson(RESULT_PATH, result), writeJson(REVIEW_PATH, result)]); return result;
}
const output = document.querySelector('#output'); window.__HAY_RACK_VALIDATION_READY__ = false;
try { const result = await validateHayRackExports(); result.checks.forEach((item) => { output.textContent += `${item.passed ? 'PASS' : 'FAIL'}: ${item.name}\n`; }); output.textContent += `Validation result: ${result.result.toUpperCase()}\n`; window.__HAY_RACK_VALIDATION_RESULT__ = result; window.__HAY_RACK_VALIDATION_READY__ = true; }
catch (error) { output.textContent += `${error.stack || error.message}\n`; window.__HAY_RACK_VALIDATION_ERROR__ = String(error.stack || error.message); }
